// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddUserRequest struct {
	Username string `json:"username"`
	Age      int    `json:"age"`
	Email    string `json:"email"`
}

type Article struct {
	Id          int    `json:"id"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	Description string `json:"description"`
	Picture     string `json:"picture"`
}

type ArticleRequest struct {
	Id int `path:"id"`
}

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
	Success bool        `json:"success"`
}

type Focus struct {
	Id       int    `json:"id"`
	Title    string `json:"title"`
	Pic      string `json:"pic"`
	Link     string `json:"link"`
	Position int    `json:"position"`
}

type FocusRequest struct {
	Id int `form:"id"`
}

type UpdateUserRequest struct {
	Id       int    `json:"id"`
	Username string `json:"username,optional"`
	Age      int    `json:"age,optional"`
	Email    string `json:"email,optional"`
}

type User struct {
	Id       int    `json:"id"`
	Username string `json:"username"`
	Age      int    `json:"age"`
	Email    string `json:"email"`
}

type UserRequest struct {
	Id int `form:"id"`
}
