// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
	Success bool        `json:"success"`
}

type Focus struct {
	Id       int    `json:"id"`
	Title    string `json:"title"`
	Pic      string `json:"pic"`
	Link     string `json:"link"`
	Position int    `json:"position"`
}

type FocusRequest struct {
	Id int `form:"id"`
}
