// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	article "zerogorm/internal/handler/article"
	focus "zerogorm/internal/handler/focus"
	user "zerogorm/internal/handler/user"
	"zerogorm/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: article.GetArticleByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: focus.GetFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oneFocus",
				Handler: focus.GetFocusByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/focus"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addUser",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/deleteUser",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUserById",
				Handler: user.GetUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateUser",
				Handler: user.UpdateUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
